/*Author: Cooper Stevens
  Resubmitted 12/3/17
  Class: CS 3810
  Professor: Dr. Cohen
 */



 --PART A)

 --1)  
 SELECT CITY_NAME, STATE_NAME, AIRPORT_ID, CARRIER_NAME, PASSENGERS
 FROM Cities NATURAL JOIN States NATURAL JOIN Airport NATURAL JOIN Airline NATURAL JOIN Flight
 WHERE ORIGIN_STATE_ABR = 'CO'; 

 --2)
 SELECT CITY_NAME, STATE_NAME, AIRPORT_ID, CARRIER_NAME, FREIGHT
 FROM Cities NATURAL JOIN States NATURAL JOIN Airport NATURAL JOIN Airline NATURAL JOIN Freight 
 WHERE ORIGIN_STATE_ABR = 'CO';

 --3)
 SELECT CITY_NAME, ORIGIN_STATE_ABR, DEST_STATE_ABR, AIRPORT_ID, CARRIER_NAME, PASSENGERS
 FROM CITIES NATURAL JOIN AIRPORT NATURAL JOIN AIRLINE NATURAL JOIN FLIGHT 
 WHERE ORIGIN_STATE_ABR != 'CO' AND DEST_STATE_ABR = 'CO';

 --4)
SELECT CITY_NAME, ORIGIN_STATE_ABR, CARRIER_NAME, DISTANCE 
FROM CITIES NATURAL JOIN AIRPORT NATURAL JOIN AIRLINE NATURAL JOIN FLIGHT 
WHERE CITY_NAME LIKE '%Denver%' AND DISTANCE>500 AND DISTANCE<1200;

