/* Author: Cooper Stevens
   Due Date: 10/8/2017 - resubmitted 11/20/2017
   Assignment: Homework Assignment #3
*/

-- Create SQL Statements, part one 

CREATE TABLE Airline(AIRLINE_ID VARCHAR(10),CARRIER VARCHAR(5),CARRIER_ENTITY VARCHAR(10),CARRIER_NAME VARCHAR(50), UNIQUE_CARRIER VARCHAR(5), UNIQUE_CARRIER_ENTITY VARCHAR(10), UNIQUE_CARRIER_NAME VARCHAR(50), WAC VARCHAR(5), CARRIER_GROUP VARCHAR(5), CARRIER_GROUP_NEW VARCHAR(5), REGION VARCHAR(15), START_DATE_SOURCE VARCHAR(15), THRU_DATE_SOURCE VARCHAR(15));

CREATE TABLE Carrier (UNIQUE_CARRIER_ENTITY VARCHAR(10), WAC VARCHAR(5), CARRIER_GROUP VARCHAR(5));

CREATE TABLE UniqueCarrierName (UNIQUE_CARRIER VARCHAR(5), UNIQUE_CARRIER_NAME VARCHAR(50));

CREATE TABLE CarrierRelation (UNIQUE_CARRIER VARCHAR(5), CARRIER VARCHAR(5));

CREATE TABLE Airport (AIRPORT_ID VARCHAR(10), AIRPORT_SEQ_ID VARCHAR(10), CITY_MARKET_ID VARCHAR(10), AIRPORT_WAC VARCHAR(5));

CREATE TABLE Cities (CITY_MARKET_ID VARCHAR(10), CITY_NAME VARCHAR(20), STATE_FIPS VARCHAR(5));

CREATE TABLE States (STATE_FIPS VARCHAR(5), STATE_NAME VARCHAR(15), STATE VARCHAR(5));

CREATE TABLE Passengers (UNIQUE_CARRIER_ENTITY VARCHAR(10), ORIGIN_AIRPORT_ID VARCHAR(10), DEST_AIRPORT_ID VARCHAR(10), PASSENGERS VARCHAR(5));

CREATE TABLE Freight (UNIQUE_CARRIER_ENTITY VARCHAR(10), ORIGIN_AIRPORT_ID VARCHAR(10), DEST_AIRPORT_ID VARCHAR(10), FREIGHT VARCHAR(5));

CREATE TABLE Mail (UNIQUE_CARRIER_ENTITY VARCHAR(10), ORIGIN_AIRPORT_ID VARCHAR(10), DEST_AIRPORT_ID VARCHAR(10), MAIL VARCHAR(5));
