
/* Author: Cooper Stevens
   Due Date: 10/8/2017 - resubmitted 11/20/2017
   Assignment: Homework Assignment #3
*/

-- Copy SQL Statements, part two to HW3

COPY Airline (AIRLINE_ID, CARRIER, CARRIER_ENTITY, CARRIER_NAME, UNIQUE_CARRIER, UNIQUE_CARRIER_ENTITY, UNIQUE_CARRIER_NAME, WAC, CARRIER_GROUP, CARRIER_GROUP_NEW, REGION, START_DATE_SOURCE, THRU_DATE_SOURCE) from 'C:\Program Files\PostgreSQL\Airline.csv' DELIMITER ',' CSV HEADER;  

COPY Carrier (UNIQUE_CARRIER_ENTITY, WAC, CARRIER_GROUP) from 'C:\Program Files\PostgreSQL\CARRER1.csv' DELIMITER ',' CSV HEADER;  

COPY UniqueCarrierName (UNIQUE_CARRIER, UNIQUE_CARRIER_NAME) from 'C:\Program Files\PostgreSQL\UniqueCarrierName1.csv' DELIMITER ',' CSV HEADER; 



COPY Airport (AIRPORT_ID, AIRPORT_SEQ_ID, CITY_MARKET_ID, AIRPORT_WAC) from 'C:\Program Files\PostgreSQL\Airport1.csv' DELIMITER ',' CSV HEADER; 

COPY Cities (CITY_MARKET_ID, CITY_NAME, STATE_FIPS) from 'C:\Program Files\PostgreSQL\Cities1.csv' DELIMITER ',' CSV HEADER;  

COPY States (STATE_FIPS, STATE_NAME, STATE) from 'C:\Program Files\PostgreSQL\States.csv' DELIMITER ',' CSV HEADER; 

COPY Passengers (UNIQUE_CARRIER_ENTITY, ORIGIN_AIRPORT_ID, DEST_AIRPORT_ID, PASSENGERS) from 'C:\Program Files\PostgreSQL\Passengers1.csv' DELIMITER ',' CSV HEADER; 

COPY Freight (UNIQUE_CARRIER_ENTITY, ORIGIN_AIRPORT_ID, DEST_AIRPORT_ID, FREIGHT) from 'C:\Program Files\PostgreSQL\Freight1.csv' DELIMITER ',' CSV HEADER; 

COPY Mail (UNIQUE_CARRIER_ENTITY, ORIGIN_AIRPORT_ID, DEST_AIRPORT_ID, MAIL) from 'C:\Program Files\PostgreSQL\Mail1.csv' DELIMITER ',' CSV HEADER; 
